
services:
  polymath-api:
    build: .
    container_name: polymath_server
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=let_me_in_please
      - DATABASE_URL=postgresql://user:password@postgres:5432/polymath_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - neo4j
      - postgres
      - redis
    volumes:
      - ./app:/code/app  # Live reload for development

  neo4j:
    image: neo4j:5.12-community
    container_name: polymath_graph
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt Protocol
    environment:
      - NEO4J_AUTH=neo4j/let_me_in_please
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_PLUGINS=["apoc"] # APOC is essential for advanced graph algorithms
    volumes:
      - neo4j_data:/data

  postgres:
    image: postgres:15-alpine
    container_name: polymath_sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polymath_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: polymath_queue
    ports:
      - "6379:6379"

volumes:
  neo4j_data:
  postgres_data: