services:
  polymath-api:
    build: .
    container_name: polymath_server
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URL=neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=let_me_in_please
      - DATABASE_DIR=/app/data
    depends_on:
      - neo4j
    volumes:
      - ./app:/app/app # Live reload for development
      - ./data:/app/data

  neo4j:
    image: neo4j:5.12-community
    container_name: polymath_graph
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt Protocol
    environment:
      - NEO4J_AUTH=neo4j/let_me_in_please
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_PLUGINS=["apoc"] # APOC is essential for advanced graph algorithms
    volumes:
      - neo4j_data:/data

  # sidecar to create an agent
  agent-setup:
    build: .
    volumes:
      - ./app:/app/app
      - ./keys:/app/keys
      - ./data:/app/data
    command: sh -c "python -u -m app.admin.create_agent --name DefaultAgent | tee /app/keys/latest_key.txt"

volumes:
  neo4j_data:
